#include <vector>
#include <iostream>
#include <string>
#include <fstream>
#include <algorithm>
#include <iomanip>
#include <sstream>
#include <limits>
#include <random>
#include <ctime>
#include <chrono>
#include <ostream>
#include <chrono>
#include <cstdlib>
#include <stdexcept>
#include <exception>
#include <numeric>
#include <iterator>
#include <ios>
#include <filesystem>
#include <list>
#include <deque>
#include <cassert>
#include <map>
#include <unordered_map>
#include <set>
#include <regex>
#include <cctype>
#include <string>
#include <locale>
#include <cwctype>
#include <iomanip>
#include <unordered_set>

using std::cerr;
using std::cin;
using std::cout;
using std::deque;
using std::endl;
using std::fixed;
using std::ifstream;
using std::istringstream;
using std::left;
using std::list;
using std::map;
using std::max;
using std::move;
using std::ofstream;
using std::ostream;
using std::right;
using std::set;
using std::setprecision;
using std::setw;
using std::sort;
using std::string;
using std::stringstream;
using std::to_string;
using std::unordered_map;
using std::unordered_set;
using std::vector;
using std::wcout;
using std::wifstream;
using std::wofstream;
using std::wstring;
using std::wstringstream;
using std::chrono::duration;
using std::chrono::high_resolution_clock;